name: Escaneo Baloncesto BetPlay

on:
  schedule:
    - cron: '0 12 * * *'  # 7:00 AM Colombia
    - cron: '0 0 * * *'   # 7:00 PM Colombia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Configurar Entorno Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Dependencias y Navegador Playwright
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright playwright-stealth
          playwright install chromium
          playwright install-deps

      - name: Ejecutar motor de Baloncesto
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python analisis_baloncesto_diario.py
